import { db } from "./index.ts";
import { countries, games } from "./schema.ts";

const defaultGames = [
  { name: "EA Sports FC 25" },
  { name: "EA Sports FC 26" },
  { name: "EA Sports FC 27" },
];

const defaultCountries = [
  { name: "Afeganistão", flagCode: "AF", shortCode: "AFE" },
  { name: "África do Sul", flagCode: "ZA", shortCode: "AFS" },
  { name: "Albânia", flagCode: "AL", shortCode: "ALB" },
  { name: "Alemanha", flagCode: "DE", shortCode: "ALE" },
  { name: "Andorra", flagCode: "AD", shortCode: "AND" },
  { name: "Angola", flagCode: "AO", shortCode: "ANG" },
  { name: "Antígua e Barbuda", flagCode: "AG", shortCode: "ATG" },
  { name: "Arábia Saudita", flagCode: "SA", shortCode: "ARA" },
  { name: "Argélia", flagCode: "DZ", shortCode: "ALG" },
  { name: "Argentina", flagCode: "AR", shortCode: "ARG" },
  { name: "Armênia", flagCode: "AM", shortCode: "ARM" },
  { name: "Aruba", flagCode: "AW", shortCode: "ARU" },
  { name: "Austrália", flagCode: "AU", shortCode: "AUS" },
  { name: "Áustria", flagCode: "AT", shortCode: "AUT" },
  { name: "Azerbaijão", flagCode: "AZ", shortCode: "AZE" },
  { name: "Bahamas", flagCode: "BS", shortCode: "BHS" },
  { name: "Bahrein", flagCode: "BH", shortCode: "BHR" },
  { name: "Bangladesh", flagCode: "BD", shortCode: "BAN" },
  { name: "Barbados", flagCode: "BB", shortCode: "BAR" },
  { name: "Belarus", flagCode: "BY", shortCode: "BLR" },
  { name: "Bélgica", flagCode: "BE", shortCode: "BEL" },
  { name: "Belize", flagCode: "BZ", shortCode: "BLZ" },
  { name: "Benim", flagCode: "BJ", shortCode: "BEN" },
  { name: "Bermudas", flagCode: "BM", shortCode: "BER" },
  { name: "Bolívia", flagCode: "BO", shortCode: "BOL" },
  { name: "Bósnia e Herzegovina", flagCode: "BA", shortCode: "BOS" },
  { name: "Botsuana", flagCode: "BW", shortCode: "BOT" },
  { name: "Brasil", flagCode: "BR", shortCode: "BRA" },
  { name: "Brunei", flagCode: "BN", shortCode: "BRU" },
  { name: "Bulgária", flagCode: "BG", shortCode: "BUL" },
  { name: "Burquina Faso", flagCode: "BF", shortCode: "BFA" },
  { name: "Burundi", flagCode: "BI", shortCode: "BDI" },
  { name: "Butão", flagCode: "BT", shortCode: "BUT" },
  { name: "Cabo Verde", flagCode: "CV", shortCode: "CPV" },
  { name: "Camboja", flagCode: "KH", shortCode: "CAM" },
  { name: "Camarões", flagCode: "CM", shortCode: "CMR" },
  { name: "Canadá", flagCode: "CA", shortCode: "CAN" },
  { name: "Catar", flagCode: "QA", shortCode: "CAT" },
  { name: "Cazaquistão", flagCode: "KZ", shortCode: "CAZ" },
  { name: "Chade", flagCode: "TD", shortCode: "CHA" },
  { name: "Chile", flagCode: "CL", shortCode: "CHI" },
  { name: "China", flagCode: "CN", shortCode: "CHN" },
  { name: "Chipre", flagCode: "CY", shortCode: "CYP" },
  { name: "Colômbia", flagCode: "CO", shortCode: "COL" },
  { name: "Comores", flagCode: "KM", shortCode: "COM" },
  { name: "Congo", flagCode: "CG", shortCode: "CGO" },
  { name: "Coreia do Norte", flagCode: "KP", shortCode: "CDN" },
  { name: "Coreia do Sul", flagCode: "KR", shortCode: "CDS" },
  { name: "Costa do Marfim", flagCode: "CI", shortCode: "CIV" },
  { name: "Costa Rica", flagCode: "CR", shortCode: "CRC" },
  { name: "Croácia", flagCode: "HR", shortCode: "CRO" },
  { name: "Cuba", flagCode: "CU", shortCode: "CUB" },
  { name: "Curaçao", flagCode: "CW", shortCode: "CUR" },
  { name: "Dinamarca", flagCode: "DK", shortCode: "DIN" },
  { name: "Djibuti", flagCode: "DJ", shortCode: "DJI" },
  { name: "Dominica", flagCode: "DM", shortCode: "DMA" },
  { name: "Egito", flagCode: "EG", shortCode: "EGI" },
  { name: "El Salvador", flagCode: "SV", shortCode: "ELS" },
  { name: "Emirados Árabes Unidos", flagCode: "AE", shortCode: "EAU" },
  { name: "Equador", flagCode: "EC", shortCode: "EQU" },
  { name: "Eritreia", flagCode: "ER", shortCode: "ERI" },
  { name: "Escócia", flagCode: "GB-SCT", shortCode: "ESC" },
  { name: "Eslováquia", flagCode: "SK", shortCode: "ESL" },
  { name: "Eslovênia", flagCode: "SI", shortCode: "ESV" },
  { name: "Espanha", flagCode: "ES", shortCode: "ESP" },
  { name: "Essuatíni", flagCode: "SZ", shortCode: "ESW" },
  { name: "Estados Unidos", flagCode: "US", shortCode: "EUA" },
  { name: "Estônia", flagCode: "EE", shortCode: "EST" },
  { name: "Etiópia", flagCode: "ET", shortCode: "ETI" },
  { name: "Fiji", flagCode: "FJ", shortCode: "FIJ" },
  { name: "Filipinas", flagCode: "PH", shortCode: "FIL" },
  { name: "Finlândia", flagCode: "FI", shortCode: "FIN" },
  { name: "França", flagCode: "FR", shortCode: "FRA" },
  { name: "Gabão", flagCode: "GA", shortCode: "GAB" },
  { name: "Gâmbia", flagCode: "GM", shortCode: "GAM" },
  { name: "Gana", flagCode: "GH", shortCode: "GAN" },
  { name: "Geórgia", flagCode: "GE", shortCode: "GEO" },
  { name: "Gibraltar", flagCode: "GI", shortCode: "GIB" },
  { name: "Granada", flagCode: "GD", shortCode: "GRD" },
  { name: "Grécia", flagCode: "GR", shortCode: "GRE" },
  { name: "Guadalupe", flagCode: "GP", shortCode: "GDL" },
  { name: "Guam", flagCode: "GU", shortCode: "GUM" },
  { name: "Guatemala", flagCode: "GT", shortCode: "GUA" },
  { name: "Guiana", flagCode: "GY", shortCode: "GUI" },
  { name: "Guiana Francesa", flagCode: "GF", shortCode: "GUF" },
  { name: "Guiné", flagCode: "GN", shortCode: "GIN" },
  { name: "Guiné-Bissau", flagCode: "GW", shortCode: "GBS" },
  { name: "Guiné Equatorial", flagCode: "GQ", shortCode: "GEQ" },
  { name: "Haiti", flagCode: "HT", shortCode: "HAI" },
  { name: "Honduras", flagCode: "HN", shortCode: "HON" },
  { name: "Hong Kong", flagCode: "HK", shortCode: "HKG" },
  { name: "Hungria", flagCode: "HU", shortCode: "HUN" },
  { name: "Iémen", flagCode: "YE", shortCode: "IEM" },
  { name: "Ilhas Cayman", flagCode: "KY", shortCode: "CAY" },
  { name: "Ilhas Cook", flagCode: "CK", shortCode: "COK" },
  { name: "Ilhas Faroé", flagCode: "FO", shortCode: "FAR" },
  { name: "Ilhas Salomão", flagCode: "SB", shortCode: "SOL" },
  { name: "Ilhas Turcas e Caicos", flagCode: "TC", shortCode: "TCA" },
  { name: "Ilhas Virgens Americanas", flagCode: "VI", shortCode: "IVA" },
  { name: "Ilhas Virgens Britânicas", flagCode: "VG", shortCode: "IVB" },
  { name: "Índia", flagCode: "IN", shortCode: "IND" },
  { name: "Indonésia", flagCode: "ID", shortCode: "IDN" },
  { name: "Inglaterra", flagCode: "GB-ENG", shortCode: "ING" },
  { name: "Irã", flagCode: "IR", shortCode: "IRA" },
  { name: "Iraque", flagCode: "IQ", shortCode: "IRQ" },
  { name: "Irlanda", flagCode: "IE", shortCode: "IRL" },
  { name: "Irlanda do Norte", flagCode: "GB-NIR", shortCode: "IRN" },
  { name: "Islândia", flagCode: "IS", shortCode: "ISL" },
  { name: "Israel", flagCode: "IL", shortCode: "ISR" },
  { name: "Itália", flagCode: "IT", shortCode: "ITA" },
  { name: "Jamaica", flagCode: "JM", shortCode: "JAM" },
  { name: "Japão", flagCode: "JP", shortCode: "JAP" },
  { name: "Jordânia", flagCode: "JO", shortCode: "JOR" },
  { name: "Kosovo", flagCode: "XK", shortCode: "KOS" },
  { name: "Kuwait", flagCode: "KW", shortCode: "KWT" },
  { name: "Laos", flagCode: "LA", shortCode: "LAO" },
  { name: "Lesoto", flagCode: "LS", shortCode: "LES" },
  { name: "Letônia", flagCode: "LV", shortCode: "LET" },
  { name: "Líbano", flagCode: "LB", shortCode: "LIB" },
  { name: "Libéria", flagCode: "LR", shortCode: "LBR" },
  { name: "Líbia", flagCode: "LY", shortCode: "LBY" },
  { name: "Liechtenstein", flagCode: "LI", shortCode: "LIE" },
  { name: "Lituânia", flagCode: "LT", shortCode: "LIT" },
  { name: "Luxemburgo", flagCode: "LU", shortCode: "LUX" },
  { name: "Macau", flagCode: "MO", shortCode: "MAU" },
  { name: "Macedônia do Norte", flagCode: "MK", shortCode: "MAC" },
  { name: "Madagascar", flagCode: "MG", shortCode: "MAD" },
  { name: "Malásia", flagCode: "MY", shortCode: "MAL" },
  { name: "Maláui", flagCode: "MW", shortCode: "MAW" },
  { name: "Maldivas", flagCode: "MV", shortCode: "MDV" },
  { name: "Mali", flagCode: "ML", shortCode: "MLI" },
  { name: "Malta", flagCode: "MT", shortCode: "MLT" },
  { name: "Marrocos", flagCode: "MA", shortCode: "MAR" },
  { name: "Martinica", flagCode: "MQ", shortCode: "MTQ" },
  { name: "Maurícia", flagCode: "MU", shortCode: "MRI" },
  { name: "Mauritânia", flagCode: "MR", shortCode: "MTN" },
  { name: "México", flagCode: "MX", shortCode: "MEX" },
  { name: "Mianmar", flagCode: "MM", shortCode: "MIA" },
  { name: "Moldávia", flagCode: "MD", shortCode: "MOL" },
  { name: "Mongólia", flagCode: "MN", shortCode: "MON" },
  { name: "Montenegro", flagCode: "ME", shortCode: "MNE" },
  { name: "Montserrat", flagCode: "MS", shortCode: "MSR" },
  { name: "Moçambique", flagCode: "MZ", shortCode: "MOZ" },
  { name: "Namíbia", flagCode: "NA", shortCode: "NAM" },
  { name: "Nepal", flagCode: "NP", shortCode: "NEP" },
  { name: "Nicarágua", flagCode: "NI", shortCode: "NIC" },
  { name: "Níger", flagCode: "NE", shortCode: "NIG" },
  { name: "Nigéria", flagCode: "NG", shortCode: "NGA" },
  { name: "Noruega", flagCode: "NO", shortCode: "NOR" },
  { name: "Nova Caledônia", flagCode: "NC", shortCode: "NCL" },
  { name: "Nova Zelândia", flagCode: "NZ", shortCode: "NZL" },
  { name: "Omã", flagCode: "OM", shortCode: "OMA" },
  { name: "País de Gales", flagCode: "GB-WLS", shortCode: "GAL" },
  { name: "Países Baixos", flagCode: "NL", shortCode: "HOL" },
  { name: "Paquistão", flagCode: "PK", shortCode: "PAQ" },
  { name: "Palestina", flagCode: "PS", shortCode: "PAL" },
  { name: "Panamá", flagCode: "PA", shortCode: "PAN" },
  { name: "Papua-Nova Guiné", flagCode: "PG", shortCode: "PNG" },
  { name: "Paraguai", flagCode: "PY", shortCode: "PAR" },
  { name: "Peru", flagCode: "PE", shortCode: "PER" },
  { name: "Polônia", flagCode: "PL", shortCode: "POL" },
  { name: "Porto Rico", flagCode: "PR", shortCode: "PUR" },
  { name: "Portugal", flagCode: "PT", shortCode: "POR" },
  { name: "Quênia", flagCode: "KE", shortCode: "QUE" },
  { name: "Quirguistão", flagCode: "KG", shortCode: "QUI" },
  { name: "República Centro-Africana", flagCode: "CF", shortCode: "RCA" },
  { name: "República Democrática do Congo", flagCode: "CD", shortCode: "RDC" },
  { name: "República Dominicana", flagCode: "DO", shortCode: "RDO" },
  { name: "República Tcheca", flagCode: "CZ", shortCode: "TCH" },
  { name: "Romênia", flagCode: "RO", shortCode: "ROM" },
  { name: "Ruanda", flagCode: "RW", shortCode: "RUA" },
  { name: "Rússia", flagCode: "RU", shortCode: "RUS" },
  { name: "Samoa", flagCode: "WS", shortCode: "SAM" },
  { name: "Samoa Americana", flagCode: "AS", shortCode: "ASA" },
  { name: "San Marino", flagCode: "SM", shortCode: "SMR" },
  { name: "Santa Lúcia", flagCode: "LC", shortCode: "SLC" },
  { name: "São Cristóvão e Névis", flagCode: "KN", shortCode: "SKN" },
  { name: "São Tomé e Príncipe", flagCode: "ST", shortCode: "STP" },
  { name: "São Vicente e Granadinas", flagCode: "VC", shortCode: "SVG" },
  { name: "Senegal", flagCode: "SN", shortCode: "SEN" },
  { name: "Serra Leoa", flagCode: "SL", shortCode: "SLE" },
  { name: "Sérvia", flagCode: "RS", shortCode: "SER" },
  { name: "Seicheles", flagCode: "SC", shortCode: "SEI" },
  { name: "Singapura", flagCode: "SG", shortCode: "SGP" },
  { name: "Síria", flagCode: "SY", shortCode: "SIR" },
  { name: "Sint Maarten", flagCode: "SX", shortCode: "SMA" },
  { name: "Somália", flagCode: "SO", shortCode: "SOM" },
  { name: "Sri Lanka", flagCode: "LK", shortCode: "SRI" },
  { name: "Sudão", flagCode: "SD", shortCode: "SUD" },
  { name: "Sudão do Sul", flagCode: "SS", shortCode: "SDS" },
  { name: "Suécia", flagCode: "SE", shortCode: "SUE" },
  { name: "Suíça", flagCode: "CH", shortCode: "SUI" },
  { name: "Suriname", flagCode: "SR", shortCode: "SUR" },
  { name: "Tailândia", flagCode: "TH", shortCode: "TAI" },
  { name: "Taipei Chinês", flagCode: "TW", shortCode: "TPE" },
  { name: "Tajiquistão", flagCode: "TJ", shortCode: "TAJ" },
  { name: "Taiti", flagCode: "PF", shortCode: "TAH" },
  { name: "Tanzânia", flagCode: "TZ", shortCode: "TAN" },
  { name: "Timor-Leste", flagCode: "TL", shortCode: "TLS" },
  { name: "Togo", flagCode: "TG", shortCode: "TOG" },
  { name: "Tonga", flagCode: "TO", shortCode: "TON" },
  { name: "Trinidad e Tobago", flagCode: "TT", shortCode: "TRI" },
  { name: "Tunísia", flagCode: "TN", shortCode: "TUN" },
  { name: "Turcomenistão", flagCode: "TM", shortCode: "TKM" },
  { name: "Turquia", flagCode: "TR", shortCode: "TUR" },
  { name: "Ucrânia", flagCode: "UA", shortCode: "UCR" },
  { name: "Uganda", flagCode: "UG", shortCode: "UGA" },
  { name: "Uruguai", flagCode: "UY", shortCode: "URU" },
  { name: "Uzbequistão", flagCode: "UZ", shortCode: "UZB" },
  { name: "Vanuatu", flagCode: "VU", shortCode: "VAN" },
  { name: "Venezuela", flagCode: "VE", shortCode: "VEN" },
  { name: "Vietnã", flagCode: "VN", shortCode: "VIE" },
  { name: "Zâmbia", flagCode: "ZM", shortCode: "ZAM" },
  { name: "Zimbábue", flagCode: "ZW", shortCode: "ZIM" },
];

async function seed() {
  await db.insert(games).values(defaultGames).onConflictDoNothing();

  const existingCountryNames = new Set(
    (await db.select({ name: countries.name }).from(countries)).map(
      ({ name }) => name,
    ),
  );
  const countriesToInsert = defaultCountries.filter(
    ({ name }) => !existingCountryNames.has(name),
  );

  if (countriesToInsert.length > 0) {
    await db.insert(countries).values(countriesToInsert);
  }

  console.log("Database seeded successfully!");
}

seed().catch((error) => {
  console.error("Failed to seed database:", error);
  process.exit(1);
});
